spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jackey35/spring-cloud-config-server.git
      uri: http://localhost:8888

  application:
    name: config-server

server:
  port: 8888